name: Infection Risk Prediction

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  run-predictor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==2.2.3
          pip install scikit-learn==1.6.1
          pip install joblib==1.5.0
          pip install requests  # If you're using requests to call ThingSpeak

      - name: Run prediction script
        run: python predict_and_alert.py
